<?php

/**
 *  Implements hook_preprocess_page(&$variables)
 */
function elx_frontend_preprocess_page(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $reset = FALSE;
  unset($variables['page']['content']);

  $config = \Drupal::config('system.site');
  $variables['site_name'] = $config->get('name');
  $variables['site_slogan'] = $config->get('slogan');
}

function elx_frontend_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $variables['current_path'] = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);

  $cachecontrol = [
    '#tag' => 'meta',
    '#attributes' => [
      'http-equiv' => 'Cache-Control',
      'content' => 'public, max-age=86400, must-revalidate',
    ],
  ];

  $themecolor = [
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'theme-color',
      'content' => '#000000',
    ],
  ];

  $variables['page']['#attached']['html_head'][] = [$cachecontrol, 'Cache-Control'];
  $variables['page']['#attached']['html_head'][] = [$themecolor, 'Theme-Color'];
}