export const FETCH_PRIMARY_NAVIGATIONS_LIST = 'FETCH_PRIMARY_NAVIGATIONS_LIST';
export const FETCH_PRIMARY_NAVIGATIONS_LIST_SUCCESS = 'FETCH_PRIMARY_NAVIGATIONS_LIST_SUCCESS';
export const FETCH_PRIMARY_NAVIGATIONS_LIST_FAILURE = 'FETCH_PRIMARY_NAVIGATIONS_LIST_FAILURE';

export const FETCH_LOGIN_BACKGROUND = 'FETCH_LOGIN_BACKGROUND';
export const FETCH_LOGIN_BACKGROUND_SUCCESS = 'FETCH_LOGIN_BACKGROUND_SUCCESS';
export const FETCH_LOGIN_BACKGROUND_FAILURE = 'FETCH_LOGIN_BACKGROUND_FAILURE';

export const FETCH_INTERACTIVE_CONTENT = 'FETCH_INTERACTIVE_CONTENT';
export const FETCH_INTERACTIVE_CONTENT_SUCCESS = 'FETCH_INTERACTIVE_CONTENT_SUCCESS';
export const FETCH_INTERACTIVE_CONTENT_FAILURE = 'FETCH_INTERACTIVE_CONTENT_FAILURE';

export const FETCH_INTERACTIVE_CONTENT_STATUS = 'FETCH_INTERACTIVE_CONTENT_STATUS';
export const FETCH_INTERACTIVE_CONTENT_STATUS_SUCCESS = 'FETCH_INTERACTIVE_CONTENT_STATUS_SUCCESS';
export const FETCH_INTERACTIVE_CONTENT_STATUS_FAILURE = 'FETCH_INTERACTIVE_CONTENT_STATUS_FAILURE';

export const FETCH_LEVELS = 'FETCH_LEVELS';
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS';
export const FETCH_LEVELS_FAILURE = 'FETCH_LEVELS_FAILURE';

export const FETCH_BRANDS_LEVELS = 'FETCH_BRANDS_LEVELS';
export const FETCH_BRANDS_LEVELS_SUCCESS = 'FETCH_BRANDS_LEVELS_SUCCESS';
export const FETCH_BRANDS_LEVELS_FAILURE = 'FETCH_BRANDS_LEVELS_FAILURE';

export const FETCH_LEVELS_STATUS = 'FETCH_LEVELS_STATUS';
export const FETCH_LEVELS_STATUS_SUCCESS = 'FETCH_LEVELS_STATUS_SUCCESS';
export const FETCH_LEVELS_STATUS_FAILURE = 'FETCH_LEVELS_STATUS_FAILURE';

export const FETCH_MODULE_LISTING = 'FETCH_MODULE_LISTING';
export const FETCH_MODULE_LISTING_SUCCESS = 'FETCH_MODULE_LISTING_SUCCESS';
export const FETCH_MODULE_LISTING_FAILURE = 'FETCH_MODULE_LISTING_FAILURE';

export const FETCH_PAGER = 'FETCH_PAGER';
export const FETCH_PAGER_SUCCESS = 'FETCH_PAGER_SUCCESS';
export const FETCH_PAGER_FAILURE = 'FETCH_PAGER_FAILURE';

export const FETCH_PRODUCTS_CAROUSEL = 'FETCH_PRODUCTS_CAROUSEL';
export const FETCH_PRODUCTS_CAROUSEL_SUCCESS = 'FETCH_PRODUCTS_CAROUSEL_SUCCESS';
export const FETCH_PRODUCTS_CAROUSEL_FAILURE = 'FETCH_PRODUCTS_CAROUSEL_FAILURE';

export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_PRODUCT_DETAIL_SUCCESS = 'FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAILURE = 'FETCH_PRODUCT_DETAIL_FAILURE';

export const FETCH_PRODUCTS_CATEGORIES = 'FETCH_PRODUCTS_CATEGORIES';
export const FETCH_PRODUCTS_CATEGORIES_SUCCESS = 'FETCH_PRODUCTS_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_CATEGORIES_FAILURE = 'FETCH_PRODUCTS_CATEGORIES_FAILURE';
export const FETCH_CURRENT_PRODUCTS_CATEGORY = 'FETCH_CURRENT_PRODUCTS_CATEGORY';

export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_PRODUCTS_LIST_SUCCESS = 'FETCH_PRODUCTS_LIST_SUCCESS';
export const FETCH_PRODUCTS_LIST_FAILURE = 'FETCH_PRODUCTS_LIST_FAILURE';

export const FETCH_VIEW_POINTS = 'FETCH_VIEW_POINTS';
export const FETCH_VIEW_POINTS_SUCCESS = 'FETCH_VIEW_POINTS_SUCCESS';
export const FETCH_VIEW_POINTS_FAILURE = 'FETCH_VIEW_POINTS_FAILURE';

export const FETCH_HOMEPAGE_LEVELS = 'FETCH_HOMEPAGE_LEVELS';
export const FETCH_HOMEPAGE_LEVELS_SUCCESS = 'FETCH_HOMEPAGE_LEVELS_SUCCESS';
export const FETCH_HOMEPAGE_LEVELS_FAILURE = 'FETCH_HOMEPAGE_LEVELS_FAILURE';

export const FETCH_HOMEPAGE_PRODUCTS = 'FETCH_HOMEPAGE_PRODUCTS';
export const FETCH_HOMEPAGE_PRODUCTS_SUCCESS = 'FETCH_HOMEPAGE_PRODUCTS_SUCCESS';
export const FETCH_HOMEPAGE_PRODUCTS_FAILURE = 'FETCH_HOMEPAGE_PRODUCTS_FAILURE';

export const FETCH_HOMEPAGE_SPOTLIGHT = 'FETCH_HOMEPAGE_SPOTLIGHT';
export const FETCH_HOMEPAGE_SPOTLIGHT_SUCCESS = 'FETCH_HOMEPAGE_SPOTLIGHT_SUCCESS';
export const FETCH_HOMEPAGE_SPOTLIGHT_FAILURE = 'FETCH_HOMEPAGE_SPOTLIGHT_FAILURE';

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';

export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS';
export const EDIT_USER_DETAILS_SUCCESS = 'EDIT_USER_DETAILS_SUCCESS';
export const EDIT_USER_DETAILS_FAILURE = 'EDIT_USER_DETAILS_FAILURE';

export const FETCH_MODULE_STATUS = 'FETCH_MODULE_STATUS';
export const FETCH_MODULE_STATUS_SUCCESS = 'FETCH_MODULE_STATUS_SUCCESS';
export const FETCH_MODULE_STATUS_FAILURE = 'FETCH_MODULE_STATUS_FAILURE';

export const FETCH_FOLDERS_LISTING = 'FETCH_FOLDERS_LISTING';
export const FETCH_FOLDERS_LISTING_SUCCESS = 'FETCH_FOLDERS_LISTING_SUCCESS';
export const FETCH_FOLDERS_LISTING_FAILURE = 'FETCH_FOLDERS_LISTING_FAILURE';

export const FETCH_VIDEO_DETAILS = 'FETCH_VIDEO_DETAILS';
export const FETCH_VIDEO_DETAILS_SUCCESS = 'FETCH_VIDEO_DETAILS_SUCCESS';
export const FETCH_VIDEO_DETAILS_FAILURE = 'FETCH_VIDEO_DETAILS_FAILURE';

export const FETCH_USER_POINTS = 'FETCH_USER_POINTS';
export const FETCH_USER_POINTS_SUCCESS = 'FETCH_USER_POINTS_SUCCESS';
export const FETCH_USER_POINTS_FAILURE = 'FETCH_USER_POINTS_FAILURE';

export const FETCH_USER_BADGES = 'FETCH_USER_BADGES';
export const FETCH_USER_BADGES_SUCCESS = 'FETCH_USER_BADGES_SUCCESS';
export const FETCH_USER_BADGES_FAILURE = 'FETCH_USER_BADGES_FAILURE';

export const FETCH_TRENDING_LISTING = 'FETCH_TRENDING_LISTING';
export const FETCH_TRENDING_LISTING_SUCCESS = 'FETCH_TRENDING_LISTING_SUCCESS';
export const FETCH_TRENDING_LISTING_FAILURE = 'FETCH_TRENDING_LISTING_FAILURE';

export const FETCH_STORY_DETAILS = 'FETCH_STORY_DETAILS';
export const FETCH_STORY_DETAILS_SUCCESS = 'FETCH_STORY_DETAILS_SUCCESS';
export const FETCH_STORY_DETAILS_FAILURE = 'FETCH_STORY_DETAILS_FAILURE';

export const FETCH_HOMEPAGE_TRENDING = 'FETCH_HOMEPAGE_TRENDING';
export const FETCH_HOMEPAGE_TRENDING_SUCCESS = 'FETCH_HOMEPAGE_TRENDING_SUCCESS';
export const FETCH_HOMEPAGE_TRENDING_FAILURE = 'FETCH_HOMEPAGE_TRENDING_FAILURE';

export const FETCH_TERMS_CONDITIONS = 'FETCH_TERMS_CONDITIONS';
export const FETCH_TERMS_CONDITIONS_SUCCESS = 'FETCH_TERMS_CONDITIONS_SUCCESS';
export const FETCH_TERMS_CONDITIONS_FAILURE = 'FETCH_TERMS_CONDITIONS_FAILURE';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const POST_NODE_COMMENT = 'POST_NODE_COMMENT';
export const POST_NODE_COMMENT_SUCCESS = 'POST_NODE_COMMENT_SUCCESS';
export const POST_NODE_COMMENT_FAILURE = 'POST_NODE_COMMENT_FAILURE';

export const FETCH_PRIVACY_POLICY = 'FETCH_PRIVACY_POLICY';
export const FETCH_PRIVACY_POLICY_SUCCESS = 'FETCH_PRIVACY_POLICY_SUCCESS';
export const FETCH_PRIVACY_POLICY_FAILURE = 'FETCH_PRIVACY_POLICY_FAILURE';

export const FETCH_LEVELS_CAROUSEL = 'FETCH_LEVELS_CAROUSEL';
export const FETCH_LEVELS_CAROUSEL_SUCCESS = 'FETCH_LEVELS_CAROUSEL_SUCCESS';
export const FETCH_LEVELS_CAROUSEL_FAILURE = 'FETCH_LEVELS_CAROUSEL_FAILURE';

export const FETCH_TOOL_DETAILS = 'FETCH_TOOL_DETAILS';
export const FETCH_TOOL_DETAILS_SUCCESS = 'FETCH_TOOL_DETAILS_SUCCESS';
export const FETCH_TOOL_DETAILS_FAILURE = 'FETCH_TOOL_DETAILS_FAILURE';

export const FLAG_NODE_CONTENT = 'FLAG_NODE_CONTENT';
export const FLAG_NODE_CONTENT_SUCCESS = 'FLAG_NODE_CONTENT_SUCCESS';
export const FLAG_NODE_CONTENT_FAILURE = 'FLAG_NODE_CONTENT_FAILURE';

export const FETCH_USER_BOOKMARKS = 'FETCH_USER_BOOKMARKS';
export const FETCH_USER_BOOKMARKS_SUCCESS = 'FETCH_USER_BOOKMARKS_SUCCESS';
export const FETCH_USER_BOOKMARKS_FAILURE = 'FETCH_USER_BOOKMARKS_FAILURE';

export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAILURE = 'FETCH_LEADERBOARD_FAILURE';

export const FETCH_FOLDERS_CATEGORY = 'FETCH_FOLDERS_CATEGORY';
export const FETCH_FOLDERS_CATEGORY_SUCCESS = 'FETCH_FOLDERS_CATEGORY_SUCCESS';
export const FETCH_FOLDERS_CATEGORY_FAILURE = 'FETCH_FOLDERS_CATEGORY_FAILURE';

export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'FETCH_SEARCH_RESULTS_FAILURE';

export const FETCH_CONTENT_TYPES = 'FETCH_CONTENT_TYPES';
export const FETCH_CONTENT_TYPES_SUCCESS = 'FETCH_CONTENT_TYPES_SUCCESS';
export const FETCH_CONTENT_TYPES_FAILURE = 'FETCH_CONTENT_TYPES_FAILURE';

export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_CATEGORY_LIST_SUCCESS';
export const FETCH_CATEGORY_LIST_FAILURE = 'FETCH_CATEGORY_LIST_FAILURE';

export const FETCH_LEVELS_NOTIFICATION = 'FETCH_LEVELS_NOTIFICATION';
export const FETCH_LEVELS_NOTIFICATION_SUCCESS = 'FETCH_LEVELS_NOTIFICATION_SUCCESS';
export const FETCH_LEVELS_NOTIFICATION_FAILURE = 'FETCH_LEVELS_NOTIFICATION_FAILURE';

export const FETCH_NEW_LAUNCHES = 'FETCH_NEW_LAUNCHES';
export const FETCH_NEW_LAUNCHES_SUCCESS = 'FETCH_NEW_LAUNCHES_SUCCESS';
export const FETCH_NEW_LAUNCHES_FAILURE = 'FETCH_NEW_LAUNCHES_FAILURE';

export const FETCH_NEW_LAUNCHES_CATEGORY = 'FETCH_NEW_LAUNCHES_CATEGORY';
export const FETCH_NEW_LAUNCHES_CATEGORY_SUCCESS = 'FETCH_NEW_LAUNCHES_CATEGORY_SUCCESS';
export const FETCH_NEW_LAUNCHES_CATEGORY_FAILURE = 'FETCH_NEW_LAUNCHES_CATEGORY_FAILURE';

export const FETCH_NODE_USER_ACTIVITIES = "FETCH_NODE_USER_ACTIVITIES";
export const FETCH_NODE_USER_ACTIVITIES_SUCCESS = "FETCH_NODE_USER_ACTIVITIES_SUCCESS";
export const FETCH_NODE_USER_ACTIVITIES_FAILURE = "FETCH_NODE_USER_ACTIVITIES_FAILURE";

export const SET_DATAPOINTS = "SET_DATAPOINTS";
export const SET_DATAPOINTS_SUCCESS = "SET_DATAPOINTS_SUCCESS";
export const SET_DATAPOINTS_FAILURE = "SET_DATAPOINTS_FAILURE";

export const FETCH_TRANSLATIONS_LIST = "FETCH_TRANSLATIONS_LIST";
export const FETCH_TRANSLATIONS_LIST_SUCCESS = "FETCH_TRANSLATIONS_LIST_SUCCESS";
export const FETCH_TRANSLATIONS_LIST_FAILURE = "FETCH_TRANSLATIONS_LIST_FAILURE";

export const FETCH_LANGUAGES_LIST = "FETCH_LANGUAGES_LIST";
export const FETCH_LANGUAGES_LIST_SUCCESS = "FETCH_LANGUAGES_LIST_SUCCESS";
export const FETCH_LANGUAGES_LIST_FAILURE = "FETCH_LANGUAGES_LIST_FAILURE";

export const SET_USER_LANGUAGE = "SET_USER_LANGUAGE";
export const SET_USER_LANGUAGE_SUCCESS = "SET_USER_LANGUAGE_SUCCESS";
export const SET_USER_LANGUAGE_FAILURE = "SET_USER_LANGUAGE_FAILURE";

export const FETCH_USER_SUGGEST = "FETCH_USER_SUGGEST";
export const FETCH_USER_SUGGEST_SUCCESS = "FETCH_USER_SUGGEST_SUCCESS";
export const FETCH_USER_SUGGEST_FAILURE = "FETCH_USER_SUGGEST_FAILURE";

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_VIDEO_CATEGORY = 'FETCH_VIDEO_CATEGORY';
export const FETCH_VIDEO_CATEGORY_SUCCESS = 'FETCH_VIDEO_CATEGORY_SUCCESS';
export const FETCH_VIDEO_CATEGORY_FAILURE = 'FETCH_VIDEO_CATEGORY_FAILURE';

export const FETCH_VIDEO_LISTING = 'FETCH_VIDEO_LISTING';
export const FETCH_VIDEO_LISTING_SUCCESS = 'FETCH_VIDEO_LISTING_SUCCESS';
export const FETCH_VIDEO_LISTING_FAILURE = 'FETCH_VIDEO_LISTING_FAILURE';

export const FETCH_TOOLS_LISTING = 'FETCH_TOOLS_LISTING';
export const FETCH_TOOLS_LISTING_SUCCESS = 'FETCH_TOOLS_LISTING_SUCCESS';
export const FETCH_TOOLS_LISTING_FAILURE = 'FETCH_TOOLS_LISTING_FAILURE';

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const FETCH_FOOTER_MENU = 'FETCH_FOOTER_MENU';
export const FETCH_FOOTER_MENU_SUCCESS = 'FETCH_FOOTER_MENU_SUCCESS';
export const FETCH_FOOTER_MENU_FAILURE = 'FETCH_FOOTER_MENU_FAILURE';

export const RESET_EMAIL = 'RESET_EMAIL';
export const RESET_EMAIL_SUCCESS = 'RESET_EMAIL_SUCCESS';
export const RESET_EMAIL_FAILURE = 'RESET_EMAIL_FAILURE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const FETCH_BRAND_LIST = 'FETCH_BRAND_LIST';
export const FETCH_BRAND_LIST_SUCCESS = 'FETCH_BRAND_LIST_SUCCESS';
export const FETCH_BRAND_LIST_FAILURE = 'FETCH_BRAND_LIST_FAILURE';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const ADD_ERROR_WITHOUT_LOGOUT = 'ADD_ERROR_WITHOUT_LOGOUT';

export const FETCH_GLOBAL_SUPPORT_EMAIL = 'FETCH_GLOBAL_SUPPORT_EMAIL';
export const FETCH_GLOBAL_SUPPORT_EMAIL_SUCCESS = 'FETCH_GLOBAL_SUPPORT_EMAIL_SUCCESS';
export const FETCH_GLOBAL_SUPPORT_EMAIL_FAILURE = 'FETCH_GLOBAL_SUPPORT_EMAIL_FAILURE';

export const FETCH_USER_SUPPORT_EMAIL = 'FETCH_USER_SUPPORT_EMAIL';
export const FETCH_USER_SUPPORT_EMAIL_SUCCESS = 'FETCH_USER_SUPPORT_EMAIL_SUCCESS';
export const FETCH_USER_SUPPORT_EMAIL_FAILURE = 'FETCH_USER_SUPPORT_EMAIL_FAILURE';

export const UPDATE_USER_FLAG = 'UPDATE_USER_FLAG';
export const UPDATE_USER_FLAG_SUCCESS = 'UPDATE_USER_FLAG_SUCCESS';
export const UPDATE_USER_FLAG_FAILURE = 'UPDATE_USER_FLAG_FAILURE';

export const FETCH_INGREDIENTS_LIST = 'FETCH_INGREDIENTS_LIST';
export const FETCH_INGREDIENTS_LIST_SUCCESS = 'FETCH_INGREDIENTS_LIST_SUCCESS';
export const FETCH_INGREDIENTS_LIST_FAILURE = 'FETCH_INGREDIENTS_LIST_FAILURE';

export const FETCH_FEATURED_CAROUSEL = 'FETCH_FEATURED_CAROUSEL';
export const FETCH_FEATURED_CAROUSEL_SUCCESS = 'FETCH_FEATURED_CAROUSEL_SUCCESS';
export const FETCH_FEATURED_CAROUSEL_FAILURE = 'FETCH_FEATURED_CAROUSEL_FAILURE';

export const FETCH_INGREDIENT_DETAIL = 'FETCH_INGREDIENT_DETAIL';
export const FETCH_INGREDIENT_DETAIL_SUCCESS = 'FETCH_INGREDIENT_DETAIL_SUCCESS';
export const FETCH_INGREDIENT_DETAIL_FAILURE = 'FETCH_INGREDIENT_DETAIL_FAILURE';

export const FETCH_KEYNOTES = 'FETCH_KEYNOTES';
export const FETCH_KEYNOTES_SUCCESS = 'FETCH_KEYNOTES_SUCCESS';
export const FETCH_KEYNOTES_FAILURE = 'FETCH_KEYNOTES_FAILURE';

export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILURE = 'FETCH_REGIONS_FAILURE';

export const FETCH_MARKETS = 'FETCH_MARKETS';
export const FETCH_MARKETS_SUCCESS = 'FETCH_MARKETS_SUCCESS';
export const FETCH_MARKETS_FAILURE = 'FETCH_MARKETS_FAILURE';

export const FETCH_RETAILERS = 'FETCH_RETAILERS';
export const FETCH_RETAILERS_SUCCESS = 'FETCH_RETAILERS_SUCCESS';
export const FETCH_RETAILERS_FAILURE = 'FETCH_RETAILERS_FAILURE';

export const FETCH_STORES = 'FETCH_STORES';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_FAILURE = 'FETCH_STORES_FAILURE';

export const FETCH_JOB_TITLE = 'FETCH_JOB_TITLE';
export const FETCH_JOB_TITLE_SUCCESS = 'FETCH_JOB_TITLE_SUCCESS';
export const FETCH_JOB_TITLE_FAILURE = 'FETCH_JOB_TITLE_FAILURE';

export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';

export const USER_VALIDATION = 'USER_VALIDATION';
export const USER_VALIDATION_SUCCESS = 'USER_VALIDATION_SUCCESS';
export const USER_VALIDATION_FAILURE = 'USER_VALIDATION_FAILURE';
